packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@tanstack/react-query': ^5.59.0
  '@t3-oss/env-core': ^0.11.1
  arctic: ^1.9.2
  eslint: ^9.12.0
  hono: ^4.6.4
  prettier: ^3.3.3
  tailwindcss: ^3.4.13
  typescript: ^5.6.2
  zod: ^3.23.8
  wrangler: ^3.80.4
  lucia: ^3.2.1

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    '@types/react': ^18.3.11
    '@types/react-dom': ^18.3.0
