packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  '@nanostores/react': ^0.8.0
  '@t3-oss/env-nextjs': ^0.11.1
  '@tanstack/react-query': ^5.59.19
  '@xystack/style-guide': ^0.2.4
  arctic: ^2.2.1
  consola: ^3.2.3
  date-fns: ^4.1.0
  eslint: ^9.14.0
  hono: ^4.6.9
  lucia: ^3.2.2
  lucide-react: ^0.454.0
  nanostores: ^0.11.3
  postcss: ^8.4.47
  prettier: ^3.3.3
  resend: ^4.0.1-alpha.0
  tailwindcss: ^3.4.14
  typescript: ^5.6.3
  wrangler: ^3.84.1
  zod: ^3.23.8
catalogs:
  react:
    '@types/react': ^18.3.12
    '@types/react-dom': ^18.3.1
    react: rc
    react-dom: rc
