name = "xystack_web"
compatibility_date = "2024-10-11"
compatibility_flags = ["nodejs_compat_v2"]
pages_build_output_dir = "./apps/web/dist"

[[d1_databases]]
binding = "DB"
database_name = "xystack"
database_id = "47a2e32c-fc99-4c30-b437-d6040e722cd8"
migrations_dir = "./packages/db/migrations"
preview_database_id = "DB"

[vars]
GITHUB_CLIENT_ID = ""
GITHUB_CLIENT_SECRET = ""
AUTH_SECRET = ""
