import { Inter } from 'next/font/google'
import { ThemeProvider } from '@xystack/ui/theme'
import { Toaster } from '@xystack/ui/sonner'
import type { Metadata } from 'next'

import '@xystack/ui/base.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider enableSystem attribute="class" defaultTheme="system">
          {children}

          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  )
}
